### ISSUE TITLE
Missing css file

### ISSUE THREAD

**Issue by Nwardezir** [gakimball/Cycleops#1]
_css/example.css_ is missing ... too bad as it totally breaks the sample page :(

**Comment by gakimball** [comment]
Wow, not sure how I never noticed that when I committed this stuff. I'll add that stuff now, sorry about that! I hope you like the plugin.

**Comment by Nwardezir** [comment]
Thanks, unfortunately, even with zepto.touch.js included, I couldn't get it handle touch gesture on a mobile using your sample file :(

**Comment by gakimball** [comment]
Alright, try it now. Right this second I can only test in iOS and with Chrome's touch event emulation, but if you run into more trouble let me know what device and browser you're using.
