### ISSUE TITLE
Demo not working in Firefox.

### ISSUE THREAD

**Issue by nicholascamp** [gakimball/Cycleops#3]
Firefox Aurora 28.0a2 on Manjaro Linux.

**Comment by nicholascamp** [comment]
ReferenceError: invalid assignment left-hand side -- jquery.cycleops.js line 36:

if (typeof options === 'object') { 
    this = $.extend(this, options);
}

**Comment by gakimball** [comment]
I'm not sure why that error is coming up in Aurora only, so I worked around it by moving the plugin's settings to their own object. I probably should have been doing that all along anyway.
